// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function PlaceholderGrid():Promise<ui.PlaceholderGrid>;
